---
version: "3.9"

services:
  static-file-server:
    image: halverneus/static-file-server:v1.8.6
    container_name: static-file-server
    restart: unless-stopped
    volumes:
      - ./site:/web
    networks:
      - caddy # upstreams 8080

networks:
  caddy:
    external: true
